import { ahmed } from "../constants/ImagePath";
import { yahya } from "../constants/ImagePath";
import { habibullah } from "../constants/ImagePath";
import { ahsan } from "../constants/ImagePath";
import { azizullah } from "../constants/ImagePath";
import { mohsin } from "../constants/ImagePath";
import { munsif } from "../constants/ImagePath";
import { mudassir } from "../constants/ImagePath";
export const chatData = [
    {
      id: 1,
      name: "Ahmed Khan",
      message: "Hey! Are you free today?",
      profilePic: ahmed,
      time: "12:15 PM",
      statusIcon: "checkmark-done",
      statusColor: "blue",
      unreadMessages: 0,
    },
    {
      id: 2,
      name: "Yahya",
      message: "Did you complete the task?",
      profilePic: yahya,
      time: "10:20 AM",
      statusIcon: "checkmark-done",
      statusColor: "gray",
      unreadMessages: 3,
    },
    {
      id: 3,
      name: "Habibullah",
      message: "Let me know when you arrive.",
      profilePic: habibullah,
      time: "8:40 AM",
      statusIcon: "checkmark",
      statusColor: "gray",
      unreadMessages: 0,
    },
    {
      id: 4,
      name: "Ahsan Javed",
      message: "See you at 5 PM!",
      profilePic: ahsan,
      time: "12:45 AM",
      statusIcon: "checkmark-done",
      statusColor: "blue",
      unreadMessages: 0,
    },
    {
      id: 5,
      name: "Mohsin Kamal",
      message: "Check your email for updates.",
      profilePic: mohsin,
      time: "Yesterday",
      statusIcon: "checkmark-done",
      statusColor: "blue",
      unreadMessages: 1,
    },
    {
      id: 6,
      name: "Munsif",
      message: "Great meeting today!",
      profilePic: munsif,
      time: "Yesterday",
      statusIcon: "checkmark-done",
      statusColor: "blue",
      unreadMessages: 0,
    },
    {
      id: 7,
      name: "Mudassir",
      message: "Can we reschedule?",
      profilePic: mudassir,
      time: "28/11/24",
      statusIcon: "checkmark-done",
      statusColor: "gray",
      unreadMessages: 2,
    },
    {
      id: 8,
      name: "Azizullah",
      message: "Thanks for the help!",
      profilePic: azizullah,
      time: "25/11/24",
      statusIcon: "checkmark",
      statusColor: "gray",
      unreadMessages: 0,
    },
    {
      id: 9,
      name: "Ghayur",
      message: "Can you call me later?",
      profilePic: "https://i.imgur.com/jPlcRZX.png",
      time: "22/11/24",
      statusIcon: "checkmark-done",
      statusColor: "blue",
      unreadMessages: 0,
    },
    {
      id: 10,
      name: "Aimal",
      message: "Let’s plan the trip!",
      profilePic: "https://i.imgur.com/q7X7uo4.png",
      time: "Previous",
      statusIcon: "checkmark-done",
      statusColor: "blue",
      unreadMessages: 0,
    },
  ];
  