import { ahmed } from "../constants/ImagePath";
export const chatData = [
    {
      id: 1,
      name: "Ahmed Khan",
      message: "Hey! Are you free today?",
      profilePic: ahmed,
      time: "12:15 PM",
      statusIcon: "checkmark-done",
      statusColor: "blue",
      unreadMessages: 0,
    },
    {
      id: 2,
      name: "Yahya",
      message: "Did you complete the task?",
      profilePic: "https://i.imgur.com/JjC0nST.png",
      time: "Yesterday",
      statusIcon: "checkmark-done",
      statusColor: "gray",
      unreadMessages: 3,
    },
    {
      id: 3,
      name: "Habibullah",
      message: "Let me know when you arrive.",
      profilePic: "https://i.imgur.com/lQqzOj8.png",
      time: "Previous",
      statusIcon: "checkmark",
      statusColor: "gray",
      unreadMessages: 0,
    },
    {
      id: 4,
      name: "Ahsan Javed",
      message: "See you at 5 PM!",
      profilePic: "https://i.imgur.com/2rSlEPQ.png",
      time: "12:45 AM",
      statusIcon: "checkmark-done",
      statusColor: "blue",
      unreadMessages: 0,
    },
    {
      id: 5,
      name: "Mohsin Kamal",
      message: "Check your email for updates.",
      profilePic: "https://i.imgur.com/P9GZ9XD.png",
      time: "Yesterday",
      statusIcon: "checkmark-done",
      statusColor: "blue",
      unreadMessages: 1,
    },
    {
      id: 6,
      name: "Munsif",
      message: "Great meeting today!",
      profilePic: "https://i.imgur.com/8VqQilU.png",
      time: "Previous",
      statusIcon: "checkmark-done",
      statusColor: "blue",
      unreadMessages: 0,
    },
    {
      id: 7,
      name: "Mudassir",
      message: "Can we reschedule?",
      profilePic: "https://i.imgur.com/ZQbGtKk.png",
      time: "Yesterday",
      statusIcon: "checkmark-done",
      statusColor: "gray",
      unreadMessages: 2,
    },
    {
      id: 8,
      name: "Azizullah",
      message: "Thanks for the help!",
      profilePic: "https://i.imgur.com/6oO7N7D.png",
      time: "12:30 AM",
      statusIcon: "checkmark",
      statusColor: "gray",
      unreadMessages: 0,
    },
    {
      id: 9,
      name: "Ghayur",
      message: "Can you call me later?",
      profilePic: "https://i.imgur.com/jPlcRZX.png",
      time: "Yesterday",
      statusIcon: "checkmark-done",
      statusColor: "blue",
      unreadMessages: 0,
    },
    {
      id: 10,
      name: "Aimal",
      message: "Let’s plan the trip!",
      profilePic: "https://i.imgur.com/q7X7uo4.png",
      time: "Previous",
      statusIcon: "checkmark-done",
      statusColor: "blue",
      unreadMessages: 0,
    },
  ];
  